var points = {
    'hardware': {
        
        'mixedAirDampers':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'compressorStage':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'outsideAirEnthalpySwithc':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
    
        'outsideAirCO2Concentration':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'highDuctRelativeHumidity':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0}},
        'supplyAirHumidity':{'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0}},
        'spaceRelativeHumimdity':{'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'humidifierEnable':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0}},
        'outdoorRelativeHumidityInput':{'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 0}},
        'returnAirRelativeHumidityInput':{'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 0}},
        'mixedAirTemperature': { 'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'outdoorRelativeHumidity': { 'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'preheatDischargeAirTemperature': {'isUsed':false, 'points':{ 'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'returnAirCO2Concentration': {'isUsed':false, 'points':{ 'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'returnAirRelativeHumidity': { 'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'returnAirTemperature': { 'isUsed':false, 'points':{'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'spaceRelatieHumidity': {'isUsed':false, 'points':{ 'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'supplyAirTemperature': {'isUsed':false, 'points':{ 'AI': 1, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'faceAnBypassDamper': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 1, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'mixedAirDampers': { 'isUsed':false, 'points':{'AI': 0, 'AO': 1, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'preheatingValve': { 'isUsed':false, 'points':{'AI': 0, 'AO': 1, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'filter1Status': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'fireShutdown': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'freezeStat': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'hiDuctRH': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'returnAirSmokeDetector': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'returnFanStatus': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'smokeEvacuation': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'smokePressurization': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'smokePurge': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'supplyAirSmokeDetector': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'supplyFanStatus': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 1, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'coolingValve': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1 }},
        'heatingValve': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1 }},
        'humidifierEnable': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'returnFanSS': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1 }},
        'smokeRelayK1': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 0 }},
        'smokeRelayK2': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 0 }},
        'supplyFanSS': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 1, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1 }}
    },
    'software': {

        'cO2ConcentrationDifferentialSetpoint':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'highReturnAirCO2Concentration':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'humidificationSetpoint':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0}},
        'netSupplyAirHumidity':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0}},
        'maximumSupplyAirHumidity':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0}},
        'humidificationSetpoint':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0}},
        'returnAirRelativeHumidityValue':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'outdoorRelativeHumidityValue':{'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 1, 'Alarm': 0, 'Graphics': 1}},
        'coolingSetpoint': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'dehumidificationSetpoint': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'heatingSetpoint': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'humidificationSetpoint': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'outdoorAirTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'preheatDischargeAirTemperatureSetpoint': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'returnAirRelativeHumidityValue': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'spaceCO2Concentration': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'spaceCO2ConcentrationSetpoint': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'spaceSetpointAdjust': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'spaceTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 1, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 0 }},
        'spaceUnoccupiedOverride': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 1, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 0, 'Graphics': 1 }},
        'schedule': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 1, 'Trend': 0, 'Alarm': 0, 'Graphics': 1 }},
        'filter1ChangeRequired': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 1 }},
        'filter2ChangeRequired': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 1 }},
        'highMixedAirTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'highPreheatDischargeAirTemperature': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'highReturnAirTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'highSpaceCO2Concentration': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'highSpaceRelativeHumiditiy': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'highSpaceTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'highSupplyAirTemperature': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'lowMixedAirTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'lowPreheatDischargeAirTemp': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'lowReturnAirTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'lowSpaceRelativeHumidity': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'lowSpaceTemperature': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'lowSupplyAirTemperature': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'returnFanFailure': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'returnFanInHand': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'returnFanRuntimeExceeded': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'supplyFanFailure': { 'isUsed':false, 'points':{'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'supplyFanInHand': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
        'supplyFanRuntimeExceeded': {'isUsed':false, 'points':{ 'AI': 0, 'AO': 0, 'BI': 0, 'BO': 0, 'AV': 0, 'BV': 0, 'Loop': 0, 'Schedule': 0, 'Trend': 0, 'Alarm': 1, 'Graphics': 0 }},
    }};

    module.exports = points;